-- =============================================================
-- Database Schema for My Personal Tech Blog
-- PostgreSQL on AWS RDS (db.t3.micro)
--
-- Tables: users, categories, posts, tags, post_tags, comments
-- =============================================================

-- ----- USERS -----
-- Admin users managed by AWS Cognito.
-- We store a local reference so we can link posts to authors.
CREATE TABLE IF NOT EXISTS users (
  id            SERIAL PRIMARY KEY,
  cognito_id    VARCHAR(255) UNIQUE NOT NULL,  -- Cognito "sub" (unique user ID)
  email         VARCHAR(255) UNIQUE NOT NULL,
  display_name  VARCHAR(100) NOT NULL,
  role          VARCHAR(20) DEFAULT 'admin',   -- 'admin' or 'editor'
  created_at    TIMESTAMP DEFAULT NOW()
);

-- ----- CATEGORIES -----
-- Each blog post belongs to one category.
-- Examples: "AWS & Cloud", "Homelab", "Certifications", "DevOps"
CREATE TABLE IF NOT EXISTS categories (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR(100) UNIQUE NOT NULL,   -- Display name
  slug          VARCHAR(100) UNIQUE NOT NULL,   -- URL-friendly: "aws-and-cloud"
  description   TEXT,
  created_at    TIMESTAMP DEFAULT NOW()
);

-- ----- POSTS -----
-- The main content table. Stores blog articles as Markdown.
CREATE TABLE IF NOT EXISTS posts (
  id                    SERIAL PRIMARY KEY,
  title                 VARCHAR(255) NOT NULL,
  slug                  VARCHAR(255) UNIQUE NOT NULL,   -- URL-friendly: "my-first-post"
  content               TEXT NOT NULL,                   -- Markdown content
  excerpt               TEXT,                            -- Short summary for post list
  cover_image_url       VARCHAR(500),                    -- S3 URL for cover image
  status                VARCHAR(20) DEFAULT 'draft',     -- 'draft', 'published', 'archived'
  featured              BOOLEAN DEFAULT FALSE,           -- Show on homepage highlight
  reading_time_minutes  INTEGER DEFAULT 0,               -- Estimated read time
  view_count            INTEGER DEFAULT 0,
  like_count            INTEGER DEFAULT 0,               -- Likes from readers
  author_id             INTEGER REFERENCES users(id),
  category_id           INTEGER REFERENCES categories(id),
  published_at          TIMESTAMP,                       -- NULL until published
  created_at            TIMESTAMP DEFAULT NOW(),
  updated_at            TIMESTAMP DEFAULT NOW()
);

-- Index for fast lookups by slug (every page visit uses this)
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
-- Index for listing published posts sorted by date
CREATE INDEX IF NOT EXISTS idx_posts_published ON posts(status, published_at DESC);

-- ----- TAGS -----
-- Tags can be added manually OR auto-generated by Amazon Comprehend.
-- The "source" column tracks where the tag came from.
CREATE TABLE IF NOT EXISTS tags (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR(100) UNIQUE NOT NULL,   -- Display name: "AWS", "Docker"
  slug          VARCHAR(100) UNIQUE NOT NULL,   -- URL-friendly: "aws", "docker"
  source        VARCHAR(20) DEFAULT 'manual',   -- 'manual' or 'comprehend'
  created_at    TIMESTAMP DEFAULT NOW()
);

-- ----- POST_TAGS -----
-- Junction table: connects posts to tags (many-to-many).
-- A post can have multiple tags, a tag can be on multiple posts.
CREATE TABLE IF NOT EXISTS post_tags (
  post_id       INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  tag_id        INTEGER REFERENCES tags(id) ON DELETE CASCADE,
  confidence    REAL,              -- Comprehend confidence score (0.0 - 1.0), NULL for manual tags
  PRIMARY KEY (post_id, tag_id)    -- Each post-tag combination is unique
);

-- ----- COMMENTS -----
-- Reader comments on blog posts. No login required to comment.
-- Sentiment is analyzed by Amazon Comprehend after submission.
CREATE TABLE IF NOT EXISTS comments (
  id              SERIAL PRIMARY KEY,
  post_id         INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  author_name     VARCHAR(100) NOT NULL,         -- Commenter's display name
  author_email    VARCHAR(255),                   -- Optional, not displayed publicly
  content         TEXT NOT NULL,
  sentiment       VARCHAR(20),                    -- Comprehend result: 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED'
  sentiment_score REAL,                           -- Confidence score (0.0 - 1.0)
  status          VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'approved', 'flagged', 'deleted'
  created_at      TIMESTAMP DEFAULT NOW()
);

-- Index for listing comments per post
CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id, created_at DESC);

-- ----- POST_AUDIO -----
-- Cache for Amazon Polly audio files (text-to-speech).
-- Stores the S3 key for each generated MP3 file.
-- Audio is generated on first request and cached here.
CREATE TABLE IF NOT EXISTS post_audio (
  post_id       INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  language      VARCHAR(5) NOT NULL,            -- Language code: 'de' or 'en'
  s3_key        VARCHAR(500) NOT NULL,           -- S3 object key: 'audio/post-1-de.mp3'
  created_at    TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (post_id, language)                -- One audio per post per language
);

-- ----- POST_TRANSLATIONS -----
-- Cache for Amazon Translate results (DE -> EN).
-- Each post can have one translation per target language.
-- Translations are generated on first request and cached here.
CREATE TABLE IF NOT EXISTS post_translations (
  post_id       INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  language      VARCHAR(5) NOT NULL,            -- Target language code: 'en'
  title         VARCHAR(500) NOT NULL,           -- Translated title
  content       TEXT NOT NULL,                   -- Translated Markdown content
  excerpt       TEXT,                            -- Translated excerpt
  created_at    TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (post_id, language)                -- One translation per post per language
);
